# Generated by Django 5.1.5 on 2025-01-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="steps",
            new_name="car_usage_time",
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="car_usage_distance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="electricity_usage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="internet_usage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="video_watching_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="walking_steps",
            field=models.IntegerField(default=0),
        ),
    ]
