# Generated by Django 5.1.5 on 2025-01-22 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_steps_dailyrecord_car_usage_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyrecord",
            unique_together={("user", "date")},
        ),
    ]
