# Generated by Django 5.1.5 on 2025-01-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_dailyrecord_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="trees_needed",
            field=models.FloatField(default=0),
        ),
    ]
