# Generated by Django 5.1.5 on 2025-01-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_dailyrecord_trees_needed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="car_usage_distance",
            new_name="carUsageDistance",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="car_usage_time",
            new_name="carUsageTime",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="carbon_saved",
            new_name="carbonSaved",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="electricity_usage",
            new_name="electricityUsage",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="internet_usage",
            new_name="internetUsage",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="public_transport_time",
            new_name="publicTransportTime",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="shower_time",
            new_name="showerTime",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="total_carbon_emission",
            new_name="totalCarbonEmission",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="trees_needed",
            new_name="treesNeeded",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="video_watching_time",
            new_name="videoWatchingTime",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="walking_steps",
            new_name="walkingSteps",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="water_consumed",
            new_name="waterConsumed",
        ),
        migrations.RenameField(
            model_name="reward",
            old_name="image_url",
            new_name="imageUrl",
        ),
        migrations.RenameField(
            model_name="reward",
            old_name="points_required",
            new_name="pointsRequired",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="total_carbon_saved",
            new_name="totalCarbonSaved",
        ),
    ]
